### ISSUE TITLE
Cleanup - simplify via S3 lifetimepolicy?

### ISSUE THREAD

**Issue by petemounce** [JetBrains/teamcity-s3-artifact-storage-plugin#1]
Taking a peek at https://github.com/JetBrains/teamcity-s3-artifact-storage-plugin/blob/master/s3-artifact-storage-server/src/main/java/jetbrains/buildServer/artifacts/s3/cleanup/S3CleanupExtension.java - I'm not sure that AWS S3 lifecycle actions are sufficiently rich by comparison, but they might be -
 https://docs.aws.amazon.com/AmazonS3/latest/dev/object-lifecycle-mgmt.html.

If it's possible, then those would simplify the plugin, and additionally mean significantly less traffic required to/from S3 when TeamCity decides it needs to list then delete things.

**Comment by dimyriy** [comment]
@petemounce, the issue has been moved to our tracker. Please monitor the progress here https://youtrack.jetbrains.com/issue/TW-60677.
