### ISSUE TITLE
Migrate existing artifacts from data dir to S3

### ISSUE THREAD

**Issue by anthonyangel** [JetBrains/teamcity-s3-artifact-storage-plugin#11]
I've enabled S3 storage, but have my historical artifacts on my data directory. Is there a migration tool to move these to S3 and reindex with the new location?

**Comment by danieljimenez** [comment]
My approach was time. Over time your old builds will expire and the cleaner will get them.

**Comment by pavelsher** [comment]
There is no migration, and at the moment we do not have plans to implement it.

**Comment by huseyint** [comment]
It would be great if migrate was an option :/

**Comment by yaegor** [comment]
Related request in TeamCity  tracker: https://youtrack.jetbrains.com/issue/TW-52778
