### ISSUE TITLE
403 when uploading with presign URL

### ISSUE THREAD

**Issue by HakShak** [JetBrains/teamcity-s3-artifact-storage-plugin#13]
We are seeing this with files that are only 12MB
`Failed to publish artifacts: Failed upload artifact path/to/file.ext to https://s3-eu-west-1.amazonaws.com/aws/query/string/of/doom. Response code received: 403.`

Seems like it takes too long to upload with the signed URL? Not sure if there is a way to get more information.

**Comment by dtretyakov** [comment]
@HakShak, in the [latest plugin build](https://teamcity.jetbrains.com/viewType.html?buildTypeId=TeamCityPluginsByJetBrains_AwsS3ArtifactStorage_TeamCityTrunk&tab=buildTypeHistoryList&guest=1) this problem should be resolved. Please try upgrading and let us know whether it solves the problem.

**Comment by dimyriy** [comment]
@HakShak, the issue has been moved to our tracker. Please let's move further discussions here https://youtrack.jetbrains.com/issue/TW-60692.
