### ISSUE TITLE
Indeterminate Artifact path

### ISSUE THREAD

**Issue by Michael-McD** [JetBrains/teamcity-s3-artifact-storage-plugin#15]
Cannot determine artifact path on S3 due to unpredictable folder name on artifact path.

The final path segment of a published artifact has an unpredictable integer as a name making it impossible to reference files uploaded.  

This prevents any further processing of the uploaded artifacts on AWS.  For example for uploading to Elastic Beanstalk in subsequent TC build steps/configurations.

Would it be possible to remove the final path segment or allow for the plugin to specify a deployment path?

**Comment by yaegor** [comment]
Hi Michael,

At this time this is a design decision not to allow custom paths with the bucket in order to be able to clean the bucket form the "unknown" files. Please check https://youtrack.jetbrains.com/issue/TW-52942. Comments to that issue with details on why do you need the custom path are welcome.

**Comment by Amdingo** [comment]
@yaegor I think that what @Michael-McD is saying is that the integer that is provided as the final folder in the artifact storage path is an integer based on the total builds that is inaccessible to any subsequent build.  So when trying to reference the S3 based artifacts of a build (specifically an elastic beanstalk) for a future step how do we pull the full S3 path?

**Comment by Amdingo** [comment]
@Michael-McD looking further into this you should pass the snapshot as a dep to your next build and then use %dep.ProjectName-BuildName.teamcity.build.id% to grab the integer.
