### ISSUE TITLE
Speed optimizations

### ISSUE THREAD

**Issue by HakShak** [JetBrains/teamcity-s3-artifact-storage-plugin#16]
- [ ] [Parallel multipart upload](http://docs.aws.amazon.com/AmazonS3/latest/dev/mpuoverview.html)
- [ ] [Parallel multipart download](https://aws.amazon.com/blogs/developer/parallelizing-large-downloads-for-optimal-speed/)
- [ ] Download/Upload multiple artifacts in parallel. Feels like it is done sequentially.

**Comment by acds** [comment]
Hi @dtretyakov 

Is this on the roadmap at all ?

We're having issues with upload to S3 timeout issues. We have a somewhat narrow pipe from out C environment to S3 and its failing our uploads - their < 100MB! But we are lucky enough to be Abe to afford GB broadband as a status - and sure others have similar issues.

```
Failed to upload artifacts into bucket processthis.packages: 
java.net.SocketException: Connection reset
```
multipart (upload) support apparently would solve our issue...

**Comment by dimyriy** [comment]
@HakShak, the issue has been moved to our tracker. Please let's move further discussions here https://youtrack.jetbrains.com/issue/TW-60693.
