### ISSUE TITLE
Not able to download the plugin

### ISSUE THREAD

**Issue by akhilanandbv003** [JetBrains/teamcity-s3-artifact-storage-plugin#19]
Can't I download this plugin normally as we do install other plugins? Can you point me to a documentation on how do i get it? I tried searching it in the available plugins but couldn't find it. Tried downloading the zip file and build it but that was a failure too.

**Comment by dtretyakov** [comment]
@akhilanandbv003, you need to [download the plugin](https://plugins.jetbrains.com/plugin/9623-s3-artifact-storage) from the TeamCity plugins gallery and install it as an [additional TeamCity plugin](https://confluence.jetbrains.com/display/TCDL/Installing+Additional+Plugins).

**Comment by akhilanandbv003** [comment]
So do I need Teamcity plugin installed on my Intellij?

**Comment by dtretyakov** [comment]
@akhilanandbv003, I send you a link on TeamCity plugin installation guide. This plugin is compatible with TeamCity only.
![image](https://user-images.githubusercontent.com/1025927/36889935-5a73e70a-1dfc-11e8-8c0f-8c7cdf22c3cb.png)
