### ISSUE TITLE
Just a zip file of the artifacts?

### ISSUE THREAD

**Issue by alexdresko** [JetBrains/teamcity-s3-artifact-storage-plugin#2]
I'd love it if the plugin could simply deploy a zip file of the artifacts to the root of the bucket. That'd make my life a ton easier.

**Comment by mariotacke** [comment]
Would it work if you make the artifact itself a zip? We are using this to package our artifact:

Project > General Settings > Artifact Paths
```
+:container => container.zip
```

**Comment by alexdresko** [comment]
Hrmmm. I didn't actually think about that. Will need to play around with the artifact configuration to make sure I can create the zip file with the directory structure I need. Thanks for the suggestion.
