### ISSUE TITLE
Backup/Restore requires artifact directory?

### ISSUE THREAD

**Issue by HakShak** [JetBrains/teamcity-s3-artifact-storage-plugin#20]
We just did a restore from a backup and noticed that none of the artifacts are there. I assume this is because we didn't restore the artifacts directory and this is where the map to S3 is?

**Comment by dtretyakov** [comment]
@HakShak, when external artifacts storage is enabled the metadata about artifacts mappings anyway is stored in the [TeamCity data directory](https://confluence.jetbrains.com/display/TCDL/TeamCity+Data+Directory) under `system\artifacts` folder.

So please ensure that this directory also was restored from the backup.

**Comment by HakShak** [comment]
Thanks for the confirmation. Might be a good idea to note this in the readme. We ended up just grabbing the artifacts.json recursively in the data directory and moving that to the new server and this restored the historical artifacts. :D
