### ISSUE TITLE
Plugin Compatibility

### ISSUE THREAD

**Issue by rnavarette** [JetBrains/teamcity-s3-artifact-storage-plugin#21]
Please update plugin compatibility on the TC plugins page.  Unfortunately learned it wasn't compatible only after downloading and installing.  Git page makes it clear, but the TC page lists it as "0+".

**Comment by rnavarette** [comment]
And, it would be excellent if this could support 10.x versions... we're unfortunately not at a point where we can upgrade just yet :(

**Comment by dtretyakov** [comment]
@rnavarette, thanks for explaining your case. At the moment the plugins repository does not support TeamCity versions and always displays them as a `0+`.

The external artifact storage was introduced in TeamCity 2017.1 and thus this plugin has such version limitations.

**Comment by rnavarette** [comment]
Thanks for the quick reply @dtretyakov.  Is there a bug filed for the plugins page displaying versions?!?! 🗡 

And as an aside: Much thanks to you and your team for some excellent products!
