### ISSUE TITLE
Can't manually enter S3 Bucket Name

### ISSUE THREAD

**Issue by kasiprasad** [JetBrains/teamcity-s3-artifact-storage-plugin#23]
The UI for this plugin will not allow manual entry of the S3 Bucket Name.

The IAM user I have been assigned has full permissions to the bucket I would like to use, but does not have permissions to list/get details of all buckets in the AWS account.

As a result, although I have selected the proper AWS region and have appropriate credentials to the specific Bucket I need, I am an unable to get the UI's drop down list populated with a list of available buckets. Instead, I get an error:

Failed to get list of buckets: Access Denied

It would be great if the plugin supported both, the ability to select from a list of available buckets or enter a bucket name manually.

Is there any way to forego the UI and set the bucket name explicitly so that I can make use of this plugin?

**Comment by kasiprasad** [comment]
After allowing the user access to list all buckets in the account, I am still facing the same issue.

I have verified that I can list all buckets and read/write to the specific bucket of interest using the same credentials from the CLI but the plugin continually indicates Access Denied.

Is there any way to further troubleshoot this?

**Comment by dtretyakov** [comment]
@kasiprasad, I've add the description about required permissions in the Readme:
https://github.com/JetBrains/teamcity-s3-artifact-storage-plugin#permissions

Usually error message is displayed under the bucket name like that:
![image](https://user-images.githubusercontent.com/1025927/38809394-9c8705d2-4183-11e8-922a-41300a98268b.png)

To get the complete error message from AWS you could navigate to the `teamcity-server.log` [server log file](https://confluence.jetbrains.com/display/TCDL/TeamCity+Server+Logs) and find the error message.

**Comment by kasiprasad** [comment]
Hi @dtretyakov,

Thanks for your response.

After checking the Team City server log - I see:

INFO - ts.s3.web.S3SettingsController - Failed to get list of buckets: Access key cannot be null. 
INFO - ts.s3.web.S3SettingsController - Failed to get list of buckets: Secret key cannot be null. 

However I have filled in both the Access and Secret keys via the Plugins' UI.

It seems like it is ignoring the values in UI. Can you confirm?

**Comment by kasiprasad** [comment]
Also tried using the default credential provider chain option and getting further:

INFO - ts.s3.web.S3SettingsController - Failed to get list of buckets: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; ...) (enable debug to see stacktrace)

Verified IAM Permissions:

ListAllMyBuckets and GetBucketLocations are provided to the user for *
DeleteObject and GetObject are provided for the specific buckets contents, for example
arn:aws:s3:::[bucket-name]/*

Please let me know if there is anything else needed.

Thanks.

**Comment by dtretyakov** [comment]
@kasiprasad, thanks for research results. When bucket location is not set plugin will use standard S3 region (US Virginia) to execute all of the operations.

We could show the additional input box for the region when "get bucket location" request fails to determine it.

**Comment by kasiprasad** [comment]
That sounds like a good compromise. 

Thanks for reviewing the issue and do let me know when such provisions are in place.

**Comment by dimyriy** [comment]
@kasiprasad, the issue has been moved to our tracker. Please let's move further discussions here https://youtrack.jetbrains.com/issue/TW-60695.
