### ISSUE TITLE
No artifact files in published location in S3 bucket

### ISSUE THREAD

**Issue by junkangli** [JetBrains/teamcity-s3-artifact-storage-plugin#25]
After configuring S3 storage as the artifact storage, the artifacts from builds are not found in the S3 bucket.

The build log does not show any error.

![image](https://user-images.githubusercontent.com/8693690/39356172-e55b4fe0-4a41-11e8-8d01-6448c0d66ac1.png)

### TeamCity Server Information
- TeamCity 2017.2.3 (build 51047)
- Enterprise mode
- AWS S3 Artifact Storage plugin (snapshot-20180425165138)

In addition, I enabled _Use Pre-Signed URLs for upload_.

**Comment by dtretyakov** [comment]
@junkangli, @Dasone could you please try to use the latest plugin build and let me know if it solves the problem: https://teamcity.jetbrains.com/viewType.html?buildTypeId=TeamCityPluginsByJetBrains_AwsS3ArtifactStorage_TeamCity20172&guest=1

**Comment by junkangli** [comment]
The plugin build from the link @dtretyakov provided gave an error at the S3 Artifacts Storage configuration page. I had to update to the latest plugin version (snapshot-20180516102353) from https://plugins.jetbrains.com/plugin/9623-aws-s3-artifact-storage.

With this plugin version, my build failed at _Publishing artifacts_ stage and there was an error message:
```
[Publishing artifacts] Failed to publish artifacts: Failed to upload artifacts into bucket teamcity-artifact...: 
java.io.IOException: Failed to upload artifact <redacted>: received response code HTTP 403. Ensure that the credentials in S3 storage profile are correct.
```

After that, I managed to sort out the AWS IAM permissions required by the TeamCity server to use the pre-signed URL option and my build artifacts are now able to publish to my S3 bucket.

**Comment by cottrellam** [comment]
When you say that you sorted out the AWS IAM permissions what exactly did you do?  I am having this same error.  When I configure the artifacts storage I have "Use Pre-Signed URLs for upload".  I can see the list of buckets to select so I would think that my user would have the permission needed but I have to be missing something if I am still getting the error.

**Comment by junkangli** [comment]
@cottrellam The IAM policy statement I used is as follows:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "s3:GetBucketLocation",
                "s3:ListAllMyBuckets"
            ],
            "Resource": [
                "arn:aws:s3:::*"
            ],
            "Effect": "Allow"
        },
        {
            "Action": "s3:ListBucket",
            "Resource": [
                "arn:aws:s3:::teamcity-artifactxxxxx"
            ],
            "Effect": "Allow"
        },
        {
            "Action": [
                "s3:GetObject",
                "s3:DeleteObject",
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3:::teamcity-artifactxxxxx/*"
            ],
            "Effect": "Allow"
        }
    ]
}
```
