### ISSUE TITLE
No artifacts after upgrade

### ISSUE THREAD

**Issue by sandonov** [JetBrains/teamcity-s3-artifact-storage-plugin#26]
Hello,
I've upgraded to latest version of TC. The upgrade was done on a new server. The one running the old version was killed. I use the `teamcity-s3-artifact-storage-plugin` and store all artifacts in S3. After restoring from a backup on the new server all artifacts are gone. I understand artifacts are not part of the backup, but in case they are in S3, ins't it possible have them back after restoring?  Maybe I need to backup something else?

Thanks

**Comment by dtretyakov** [comment]
@sandonov, artifact storage plugins are rely on `%TeamCityDataDir%\system\artifacts\` directory where for each build is stored metadata about published external artifacts in `.teamcity\artifacts.json` file:
https://confluence.jetbrains.com/display/TCDL/Configuring+Artifacts+Storage#ConfiguringArtifactsStorage-Externalpluginimplementation

Currently it's not a part of Backup, so you need to manually backup build artifacts. Could you please file an issue in the [TeamCity tracker](https://youtrack.jetbrains.com/issues/TW) to support use case with backup of external artifacts metadata?

**Comment by sandonov** [comment]
@dtretyakov , I've done some troubleshooting and found exactly what you're explained. For the time being I've setup a small script that backs up all `artifacts.json` files and restores them back on a server rebuild along with backup. However, would be nice this feature to be implemented for the `s3-artifacts-plugin` since the actual artifacts are in `s3` 
Will create an issue in the tracker. Thanks
