### ISSUE TITLE
Getting 403 when a bucket has deny all policy

### ISSUE THREAD

**Issue by yaron-idan** [JetBrains/teamcity-s3-artifact-storage-plugin#28]
I'm trying to use the plugin on an account that has a bucket with a deny all policy (except for a specific IAM role, assumed by an EC2 instance which is the sole entity privileged to use it).

Unfortunately, I cannot grant the user owning the credentials access to this bucket, as that will defy our security policy. 
Since this is not the bucket I intend to use for the artifacts, I don't see why this error shouldn't be just ignored and omit the deny-all bucket from the combo box.

This is the error message I'm receiving, I've confirmed with AWS support that the bucket producing the error is the deny all bucket.
```
Failed to get list of buckets: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: <redacted>; S3 Extended Request ID: <redacted>)
```
Steps to reproduce - 
Create a bucket with a deny all policy -
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Deny",
      "Principal": "*",
      "Action": "s3:*",
      "Resource": [
        "arn:aws:s3:::bucket-name",
        "arn:aws:s3:::bucket-name/*"
      ],
      "Condition": {
        "StringNotLike": {
          "aws:userId": [
            "userid:*",
            "111111111111"
          ]
        }
      }
    }
  ]
}

```
Then try to configure an artifact storage using the plugin with credentials of any other user than the one specified in the policy.

**Comment by dimyriy** [comment]
@yaron-idan, the issue has been moved to our tracker. Please monitor the progress here https://youtrack.jetbrains.com/issue/TW-60697.
