### ISSUE TITLE
Is Ceph supported as well?

### ISSUE THREAD

**Issue by yakimant** [JetBrains/teamcity-s3-artifact-storage-plugin#29]

**Comment by Christoffer-Green** [comment]
@yakimant Did you get this working?
I'm trying to use a custom endpoint, but keep getting:
`Failed to process 'buckets' request: null (Service: Amazon S3; Status Code: 400; Error Code: InvalidArgument; Request ID: null; S3 Extended Request ID: null)`
Tried increasing the log level of the server log, but the full stacktrace didn't really help. 
Have multiple other integrations against this Ceph S3 endpoint, but can't get this up and running.

**Comment by dimyriy** [comment]
@yakimant, @Christoffer-Green, the issue has been moved to our tracker. Please, let's move further discussions here https://youtrack.jetbrains.com/issue/TW-60698.
