### ISSUE TITLE
Minio support?

### ISSUE THREAD

**Issue by asychev** [JetBrains/teamcity-s3-artifact-storage-plugin#3]
Can you add ability to change endpoint so https://minio.io/ can be supported too?

**Comment by Tigro** [comment]
+1 for custom endpoint.

**Comment by dtretyakov** [comment]
@asychev, @Tigro, in the [latest plugin build](https://teamcity.jetbrains.com/repository/download/TeamCityPluginsByJetBrains_AwsS3ArtifactStorage_TeamCityTrunk/.lastSuccessful/s3-artifact-storage.zip?guest=1) it's possible to use Minio service with a settings like that:
![image](https://user-images.githubusercontent.com/1025927/33235235-2197a14c-d234-11e7-8d39-561bd447015b.png)

Please check it and let me know if everything works fine in your environment.

**Comment by yaegor** [comment]
Related issue in TeamCity tracker: https://youtrack.jetbrains.com/issue/TW-52059
