### ISSUE TITLE
Download for Indore-2018.1.x doesn't work

### ISSUE THREAD

**Issue by prochan2** [JetBrains/teamcity-s3-artifact-storage-plugin#30]
It seems that builds of the Indore-2018.1.x branch do not have artifacts publishing configured.

**Comment by dtretyakov** [comment]
@prochan2, thanks for reporting, was [fixed](https://teamcity.jetbrains.com/viewType.html?buildTypeId=TeamCityPluginsByJetBrains_AwsS3ArtifactStorage_TeamCity20181&guest=1).
