### ISSUE TITLE
Report progress of publishing to S3

### ISSUE THREAD

**Issue by tallior** [JetBrains/teamcity-s3-artifact-storage-plugin#33]
Currently when artifacts are published, no progress is displayed in the TeamCity UI.

Sometimes it takes a lot of time, and it could be very useful to show some sort of progress indicator (percentage?) to see that the upload actually is making any progress and not stuck.

**Comment by dimyriy** [comment]
@tallior, the issue has been moved to our tracker. Please, feel free to vote for the feature here https://youtrack.jetbrains.com/issue/TW-60700.
