### ISSUE TITLE
Add public-read ACL option for uploaded files

### ISSUE THREAD

**Issue by yakimant** [JetBrains/teamcity-s3-artifact-storage-plugin#34]
Please add this option, as we need files to be accessible form our Ceph instance without authorization (it's safe inside internal network).

**Comment by yakimant** [comment]
Changed the bucket policy to read for everyone as a workaround.

**Comment by dimyriy** [comment]
@yakimant , the issue has been moved to our tracker. Please, feel free to vote for the feature here https://youtrack.jetbrains.com/issue/TW-60701.

**Comment by yakimant** [comment]
We just set up policy for the whole bucket.
