### ISSUE TITLE
Allow archive expansion

### ISSUE THREAD

**Issue by mrmod** [JetBrains/teamcity-s3-artifact-storage-plugin#35]
As an artifact stored in S3, and the archive is a Zip, Tar, Gzip, etc, then the archive should be expandable in the `Artifacts` tab of a successful build.

This would be working if on the `Artifacts` tab for a successful build, the tree allowed the expansion of an archive stored in S3.

This behavior is available on the filesystem-backed artifact storage, yet not on the S3 storage. My suspicion is the fs-backed artifact is unpacked in memory or temp, yet the S3 HTTP GET makes this practice cumbersome. A parity of behavior in this regard would be nice.

**Comment by dimyriy** [comment]
@mrmod, the issue has been moved to our tracker. Please monitor the progress there https://youtrack.jetbrains.com/issue/TW-60677.
