### ISSUE TITLE
Upload fails for large artifacts

### ISSUE THREAD

**Issue by rdavisunr** [JetBrains/teamcity-s3-artifact-storage-plugin#37]
Various artifacts we would like to upload to S3 are large in size (as much as 20 GBs and larger).

When trying to publish artifacts of this size, we receive the following error message:

``[Publishing artifacts] Failed to publish artifacts: Failed to upload artifacts into bucket ets-devops-artifacts-qvbj-na: java.lang.RuntimeException: Connection reset by peer: socket write error``

[Amazon does have a single Put limit of 5GB.](https://docs.aws.amazon.com/AmazonS3/latest/dev/UploadingObjects.html)

I reviewed the code in this repo and it would seem to be a single Put operation subject to the 5GB limit. Can you confirm?

That same Amazon link says:
``The multipart upload API is designed to improve the upload experience for larger objects. You can upload objects in parts. These object parts can be uploaded independently, in any order, and in parallel. You can use a multipart upload for objects from 5 MB to 5 TB in size. For more information, see Uploading Objects Using Multipart Upload API.``

If this current plugin is subject to the 5GB limitation, can you add an enhancement to support multipart upload of artifacts larger than 5GB ?

**Comment by codefox42** [comment]
This is also a show stopper for us. Besides this I am unsure if feature requests regarding this plugin should be posted via GitHub or [YouTrack](https://youtrack.jetbrains.com/issues/TW) - advise would be very welcome!

**Comment by dimyriy** [comment]
Please follow this ticket in YouTrack for updates:

https://youtrack.jetbrains.com/issue/TW-66202
