### ISSUE TITLE
Local agents fail to upload to S3

### ISSUE THREAD

**Issue by danieljimenez** [JetBrains/teamcity-s3-artifact-storage-plugin#4]
Hi, I'm investigating an issue where my non-cloud agents (all macOS) fail to upload to s3. The output in the logs is:

```
[12:42:39]	Failed to publish artifacts: AWS error: Forbidden
[12:42:39]	Failed to publish artifacts: AWS error: Forbidden
[12:42:39]	
Service:             Amazon S3
HTTP Status Code:    403
AWS Error Code:      403 Forbidden
Error Type:          Client
Request ID:          D84A06061D51B1E1
[12:42:39]	Artifacts size 0 B is 1 B less than the provided threshold 1 B
[12:42:39]	Build failure condition: Fail build if artifacts size is less than 1 B
```

I've enabled `debug-all` in the diagnostics menu, but didn't see any reference to s3 or that request ID. 

I opened a case with Amazon, as I had a hunch the plugin wasn't sending the right credentials, but they cannot look into the request without the extended request id as well as the request id. I'll file another issue for logging the extended request id.

**Comment by danieljimenez** [comment]
See #5 for case regarding extended request id. A secondary question, is there a way to enable addtional logging for this plugin?

**Comment by danieljimenez** [comment]
I enabled S3 access logging and found the entries by the local agents, they seem to be making the requests anonymously as I suspected. Here is a log output line:

`61a2d18f3fd2087f6f795a229c804abb85fed75a666cfb44ba3ec20e594571af	foreflight-teamcity	30/Apr/2017:20:40:47 +0000	127.0.0.1	-	1E446506D29F5F3B	REST.HEAD.OBJECT	CiBuilds_Test/CiBuilds_Test_Dj/276407	HEAD	/foreflight-teamcity/CiBuilds_Test/CiBuilds_Test_Dj/276407	HTTP/1.1	403	AccessDenied	243	-	119	-	"-"	"JetBrains TeamCity 2017.1.1, aws-sdk-java/1.11.86 Mac_OS_X/10.11.6 Java_HotSpot(TM)_64-Bit_Server_VM/25.102-b14/1.8.0_102"`

**Comment by danieljimenez** [comment]
Any other info I can provide for this case?

**Comment by dtretyakov** [comment]
@danieljimenez, we could not reproduce it on the clean machine with TeamCity and local build agent on Mac OS.

Maybe you have installed some software which behaves like a proxy on this machine? Is it reproducible on all build agents with Mac OS?

**Comment by danieljimenez** [comment]
I have ten agents running macOS that we rebuild from scratch every macOS release. I'm 99% confident it's an issue with either macOS agents or non-ec2 agents. Unfortunately my only non-ec2 agents are Macs.

**Comment by danieljimenez** [comment]
Any updates on this? Any info I can provide? As I said I have several machines experiencing this. Where would I put AWS credentials for them? I'm passing in ENV variables to the build...

**Comment by dtretyakov** [comment]
@danieljimenez, sorry for delay. You could [try upgrading the plugin](https://teamcity.jetbrains.com/viewType.html?buildTypeId=TeamCityPluginsByJetBrains_AwsS3ArtifactStorage_TeamCityTrunk&tab=buildTypeHistoryList&guest=1) and use Signed URL option which allows to generate upload links on the TeamCity server and as result you no more need to deal with S3 permissions on build agents.

**Comment by dimyriy** [comment]
@danieljimenez, the issue has been moved to our tracker. Please, let's move further discussions here https://youtrack.jetbrains.com/issue/TW-60689.
