### ISSUE TITLE
Error uploading artifacts larger than 5GB

### ISSUE THREAD

**Issue by magJ** [JetBrains/teamcity-s3-artifact-storage-plugin#45]
Attempting to upload an artifact larger than 5GB causes a "Broken pipe (Write failed)" error.  

This is because S3 requires files larger than 5GB to be uploaded using the multi-part API, and closes the connection if it receives a regular put object request with a Content-Length greater than 5GB.

Please add support for uploading large artifacts.

**Comment by dimyriy** [comment]
Please, follow the issue in our tracker https://youtrack.jetbrains.com/issue/TW-67582
