### ISSUE TITLE
Allow using IAM role for authentication

### ISSUE THREAD

**Issue by tkowalcz** [JetBrains/teamcity-s3-artifact-storage-plugin#6]
I am not entirely sure but looks like this plugin does not support using IAM role based authentication. I have tried it on an actual TC with (presumably) proper roles. I have also browsed the code. Excuse me if I am mistaken.

Summary:
Our TeamCity agents have IAM roles assigned with proper permissions. There is no need to provide access key/secret key or use STS. This seems to be the preferred and most secure way of accessing AWS resources if running on EC2 (see the [docs](http://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2.html)).

This is already nicely supported by Amazon Java SDK. What do you think?

**Comment by quelgar** [comment]
Here's how I got it to work, although I can't say this is necessarily the best way:

Make a role for the agents. It needs read/write permissions for your S3 bucket, and it needs a trust policy similar to:

``` json
        "AssumeRolePolicyDocument" : {
          "Statement" : [
            {
              "Effect" : "Allow",
              "Principal" : {
                "AWS" : "*"
              },
              "Condition" : {
                "StringEquals" : {
                  "sts:ExternalId" : "<External ID from TeamCity S3 settings page>"
                }
              },
              "Action" : "sts:AssumeRole"
            },
            {
              "Effect" : "Allow",
              "Principal" : {
                "Service" : "ec2.amazonaws.com"
              },
              "Action" : "sts:AssumeRole"
            }
          ],
          "Version" : "2012-10-17"
        }
```

Put the role's ARN (`arn:aws:iam::XXX/role/YYY`) in the TeamCity S3 artifact settings, and assign the role to your agent instances.

The `"Service" : "ec2.amazonaws.com"` entry allows the agents to assume the role and publish the artifacts.. The `sts:ExternalId` entry allows the TeamCity server to assume the role and read the artifacts.

**Comment by danieljimenez** [comment]
I was referring to my non AWS instances.

**Comment by dimyriy** [comment]
@tkowalcz, the issue has been moved to our tracker. Please, monitor progress here https://youtrack.jetbrains.com/issue/TW-60690.
