### ISSUE TITLE
About build.number

### ISSUE THREAD

**Issue by marchenkov** [JetBrains/teamcity-s3-artifact-storage-plugin#7]
Hello.

Can you explain me how I can define path on amazon s3?

I need s3/bucket/ build.number / artifacts.zip

But I receive s3/bucket/ teamcity.build.id / artifacts.zip

As on screenshow I need build.number 2.0.10 for example in amazon, but receive 283.

How define build folder for this?

![2017-05-22_23-37-15](https://cloud.githubusercontent.com/assets/6850491/26329472/ba59e208-3f47-11e7-9101-b12483afc4a7.png)

**Comment by nskvortsov** [comment]
@marchenkov the build number is not unique. Using it as the destination path may cause collisions and loss of artifacts

**Comment by marchenkov** [comment]
But I need this, with old plugin https://github.com/guardian/teamcity-s3-plugin build path looks like

projectname::buildname/buildnumber.

**Comment by yaegor** [comment]
@marchenkov At this time there is no way to customize the path within the bucket.
Could you please detail why do you need that and how should the case with clashing build numbers be resolved?

**Comment by marchenkov** [comment]
When I download build #43 I know to use url looks like: s3/BuildName/43/artifacts.zip.
With your system I don't know what put in I need build #43 - like 545 or 985 (just one way to look in teamcity): s3/BuildName/XXX/artifacts.zip

**Comment by danieljimenez** [comment]
That's not really what this plugin is designed to do.

**Comment by yaegor** [comment]
@marchenkov If you "know" the build number, you can try to "know" TeamCity build id the same way. Also, you can execute a call to TeamCity to "map" the build number to the S3 bucket URL, even getting pre-signed S3 URL if necessary.

I do understand the intent here, but weighing the options we decided not to allow customization of bucket path at this time. It would still be interesting to get the use case details as thee can help us understand how important is this case.

**Comment by simonbuchan** [comment]
We just have a `aws s3 cp` command at the end of our build, which we deploy from, it works fine.

At the moment if we moved to this plugin, we would have a CI config that creates the artifacts, uploads them to S3, then a deploy config  that downloads them from S3 just to upload them to S3 again. Even with a solution for that, per-config build number is directly visible on the UI in order to try things like `./deploy --env dev --build 123`. We don't have strong reasons to use TC artifacts, but who knows, maybe someone else does?

**Comment by marchenkov** [comment]
Very cool replacement of old plugin https://github.com/guardian/teamcity-s3-plugin that not сompatible with your (now I need yo use teamcity to know url of build). 

Use your `cool` plugin themselves, I'm plan use old plugin.

**Comment by dtretyakov** [comment]
@marchenkov, feel free to specify custom path format as mentioned in the [configuration section](https://github.com/JetBrains/teamcity-s3-artifact-storage-plugin#configuring) in the [latest plugin build](https://teamcity.jetbrains.com/viewType.html?buildTypeId=TeamCityPluginsByJetBrains_AwsS3ArtifactStorage_TeamCityTrunk).

**Comment by marchenkov** [comment]
@dtretyakov Hi Dmitry. How I can use storage.s3.path.prefix in latest release? Can you help me?

**Comment by yaegor** [comment]
Related issue in TeamCity tracker: https://youtrack.jetbrains.com/issue/TW-52942

**Comment by V1k3s** [comment]
Has this code change been implmented into TeamCity 2018.2.3 as part of the standard product? I'm trying to use the described functionality of storage.s3.path.prefix but it appears to be having no effect... Thanks!

**Comment by marchenkov** [comment]
> Has this code change been implmented into TeamCity 2018.2.3 as part of the standard product? I'm trying to use the described functionality of storage.s3.path.prefix but it appears to be having no effect... Thanks!

No

**Comment by V1k3s** [comment]
OK - That'll be why it's not working then

Thanks for getting back on this so quickly.
