### ISSUE TITLE
store build logs in same way as artefacts in S3

### ISSUE THREAD

**Issue by bykes** [JetBrains/teamcity-s3-artifact-storage-plugin#8]
Hi,

As build logs are handled in similar way to artefacts in TeamCity would it be possible to store them in s3 as well.
This would allow to move all build related data outside team city server.

Cheers
bykes

**Comment by dtretyakov** [comment]
@bykes, thanks for feature request. It requires changes in TeamCity core, so I moved it into TeamCity tracker: https://youtrack.jetbrains.com/issue/TW-50436

Please vote and watch for it.
