### ISSUE TITLE
Performance Monitor tab not shown when S3 plugin is enabled.

### ISSUE THREAD

**Issue by bykes** [JetBrains/teamcity-s3-artifact-storage-plugin#9]
While using S3-plugin the Performance Monitor stop working.
I got following error in my logs:
`[09:51:24][Publishing artifacts] Artifacts path '/root/agent/myagent/system/perfmon/temp/perfmon.csv, /root/agent/myagent/temp/agentTmp/build_stages.txt' not found
`
There is no perfmon files neither the report tab.

**Comment by pavelsher** [comment]
Unfortunately this bug is inside TeamCity, not in the S3 plugin. Please watch for this request: https://youtrack.jetbrains.com/issue/TW-51452
